version: '3'
services:
  elasticsearch:
    image: elasticsearch:${ES_VERSION}
    environment:
      - ELASTIC_PASSWORD=password
      - xpack.security.enabled=true
      - discovery.type=single-node
    network_mode: host
