version: '3'
services:
  elasticsearch:
    image: elasticsearch:${ES_VERSION}
    environment:
      - ELASTIC_PASSWORD=password
      - discovery.type=single-node
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    network_mode: host
