# This setup is heavily inspired by
# https://hashrocket.com/blog/posts/build-the-ultimate-elixir-ci-with-github-actions

name: Elixir CI

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        elixir:
          - 1.10.4
          - 1.13.4
          - 1.14.2

        otp:
          - 23.3.4.18
          - 24.3.4.6
          - 25.2

        # For a list of compatible ElasticSearch+Kibana versions, see
        # https://www.elastic.co/support/matrix#matrix_compatibility
        elasticsearch:
          - 7.6.0

        kibana:
          - 7.6.2

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Retrieve Mix Dependencies Cache
      uses: actions/cache@v1
      id: mix-cache
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: Install Dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: mix deps.get

    - name: Check Formatting
      run: mix format --check-formatted

    - name: Run Credo
      run: mix credo --strict

    - name: Retrieve PLT Cache
      uses: actions/cache@v1
      id: plt-cache
      with:
        path: priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-v1-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: Create PLTs
      if: steps.plt-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p priv/plts
        mix dialyzer --plt

    - name: Run dialyzer
      run: mix dialyzer --no-check --halt-exit-status

    - name: Setup ElasticSearch
      run: ES_VERSION=${{matrix.elasticsearch}} KIBANA_VERSION=${{matrix.kibana}} docker-compose up -d

    - name: Sleepy Time (Wait for ElasticSearch and Kibana to boot up)
      run: |
        git clone https://github.com/vishnubob/wait-for-it
        ./wait-for-it/wait-for-it.sh -t 30 localhost:9200
        ./docker/wait_for_kibana.sh

    - name: Run Tests
      run: mix test --include integration
